# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-northeast-2"
  # Only these AWS Account IDs may be operated on by this template
  default_tags {
      tags = {
      Create-by = "Terraform"
      }
    }
}
